# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G9eT8LgoAC0tb5d9JapWmgbepF9Vremt
"""

import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_selection import SequentialFeatureSelector
import warnings
warnings.filterwarnings('ignore')

train_df = pd.read_csv('train_scaled.csv')
X_train = train_df.drop(columns=['case', 'result'])
y_train = train_df['result']

best_overall_score = 0
best_k = 0
best_features = []

for k in range(3, 16, 2):
    knn = KNeighborsClassifier(n_neighbors=k)
    sfs = SequentialFeatureSelector(knn, n_features_to_select= 4, direction='forward', cv=5)
    sfs.fit(X_train, y_train)


    selected_features = X_train.columns[sfs.get_support()].tolist()
    X_train_selected = X_train[selected_features]
    scores = cross_val_score(knn, X_train_selected, y_train, cv=5)
    avg_score = scores.mean()

    print(f"當 k={k:2d} 時 | 5-Fold 平均準確率: {avg_score:.4f}")

    if avg_score > best_overall_score:
        best_overall_score = avg_score
        best_k = k
        best_features = selected_features

print("\n" + "="*50)
print(f"最佳 k 值: {best_k}")
print(f"最高準確率: {best_overall_score:.4f} ({(best_overall_score*100):.2f}%)")
print(f"篩選出的特徵組合 ({len(best_features)}個):")
for feature in best_features:
    print(f" - {feature}")
print("="*50)

import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

train_df = pd.read_csv('train_scaled.csv')
val_df = pd.read_csv('val_scaled.csv')

features = ['perimeter', 'aspectRatio', 'mean', 'contrast']
X_train = train_df[features]
y_train = train_df['result']
X_val = val_df[features]
y_val = val_df['result']

knn = KNeighborsClassifier(n_neighbors=11)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_val)

print(f"最終準確率 (Accuracy): {accuracy_score(y_val, y_pred):.4f}")
print("\n詳細分類報告 (Precision, Recall, F1-score):")
print(classification_report(y_val, y_pred))

print("\n混淆矩陣 (Confusion Matrix):")
print(confusion_matrix(y_val, y_pred))

"""### 嘗試調整預測門檻以提升 MALIGNANT Recall
不直接使用 `predict()`，而是透過 `predict_proba()` 獲取機率
"""

import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# 確保模型使用最佳參數重新訓練
knn_best = KNeighborsClassifier(n_neighbors=11)
knn_best.fit(X_train[features], y_train)

# 獲取預測機率 [P(BENIGN), P(MALIGNANT)]
y_probs = knn_best.predict_proba(X_val[features])

# 找到 'MALIGNANT' 在 classes_ 中的索引
malignant_idx = np.where(knn_best.classes_ == 'MALIGNANT')[0][0]

# 設定一個較低的門檻，例如 0.4 (只要機率大於 40% 就判斷為惡性)
threshold = 0.4
y_pred_custom = np.where(y_probs[:, malignant_idx] >= threshold, 'MALIGNANT', 'BENIGN')

print(f"--- 門檻調整為 {threshold} 的結果 ---")
print(f"最終準確率 (Accuracy): {accuracy_score(y_val, y_pred_custom):.4f}")
print("\n詳細分類報告:")
print(classification_report(y_val, y_pred_custom))

print("\n混淆矩陣:")
print(confusion_matrix(y_val, y_pred_custom))

"""### Recall"""

import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.metrics import make_scorer, recall_score
import warnings
import time # Import the time module
warnings.filterwarnings('ignore')

# 1. 讀取你專屬的訓練集資料
train_df = pd.read_csv('train_scaled.csv')
X_train = train_df.drop(columns=['case', 'result'])
y_train = train_df['result']

# 🔥 關鍵核心：建立一個專門鎖定 "MALIGNANT" 的 Recall 評分器
recall_malignant_scorer = make_scorer(recall_score, pos_label='MALIGNANT')

best_overall_score = 0
best_k = 0
best_features = []

start_overall_time = time.time() # Record overall start time

for k in range(3, 16, 2):
    iteration_start_time = time.time() # Record iteration start time

    knn = KNeighborsClassifier(n_neighbors=k)

    sfs = SequentialFeatureSelector(
        knn,
        n_features_to_select=5,
        direction='forward',
        cv=5,
        scoring=recall_malignant_scorer
    )
    sfs.fit(X_train, y_train)

    selected_features = X_train.columns[sfs.get_support()].tolist()
    X_train_selected = X_train[selected_features]

    scores = cross_val_score(knn, X_train_selected, y_train, cv=5, scoring=recall_malignant_scorer)
    avg_score = scores.mean()

    iteration_end_time = time.time() # Record iteration end time
    iteration_duration = iteration_end_time - iteration_start_time

    print(f"當 k={k:2d} 時 | 5-Fold 平均 Recall: {avg_score:.4f} (耗時: {iteration_duration:.2f} 秒)")

    if avg_score > best_overall_score:
        best_overall_score = avg_score
        best_k = k
        best_features = selected_features

end_overall_time = time.time() # Record overall end time
total_elapsed_time = end_overall_time - start_overall_time

print("\n" + "="*50)
print(f"最佳 k 值: {best_k}")
print(f"最高 Recall: {best_overall_score:.4f} ({(best_overall_score*100):.2f}%)")
print(f"篩選出的特徵組合 ({len(best_features)}個):")
for feature in best_features:
    print(f" - {feature}")
print(f"總執行時間: {total_elapsed_time:.2f} 秒") # Print total elapsed time
print("="*50)

import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


train_df = pd.read_csv('train_scaled.csv')
val_df = pd.read_csv('val_scaled.csv')
features = ['perimeter', 'boundary_roughness', 'contrast', 'energy', 'entropy']

X_train = train_df[features]
y_train = train_df['result']
X_val = val_df[features]
y_val = val_df['result']

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_val)

print(f"最終總準確率 (Accuracy): {accuracy_score(y_val, y_pred):.4f}")
print(classification_report(y_val, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_val, y_pred))

# recall 70% 以上
precision_curve_D, recall_curve_D, thresholds_D = precision_recall_curve(y_val, y_proba_D)
valid_indices_D = np.where(recall_curve_D[:-1] == 0.8378)[0]

if len(valid_indices_D) > 0:
    best_idx_D = valid_indices_D[-1]
    optimal_threshold_D = thresholds_D[best_idx_D]
    print(f"  使 Recall >= 70%，決策閾值設定為：{optimal_threshold_D:.4f}")
else:
    optimal_threshold_D = 0.35
    print(f"  無法達成 Recall >= 70%，閾值為：{optimal_threshold_D:.4f}")
